version: "3.7"
services:
  server:
    build:
      context: ./
    container_name: node-pokemon-api
    image: node-pokemon-api
    ports:
      - "8000:8000"
    networks:
      - backend
    links:
      - mariadb
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
